apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ncu4tswdw-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ncu4tswdw-java-springboot-gitops